controller_manager:
  ros__parameters:
    update_rate: 50

left_wheel_joint:
  ros__parameters:
    command_interfaces: ["velocity"]
    state_interfaces: ["velocity"]

right_wheel_joint:
  ros__parameters:
    command_interfaces: ["velocity"]
    state_interfaces: ["velocity"]

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    cmd_vel_timeout: 0.5
    publish_rate: 50
